import type { Metadata } from "next";
import "./globals.css";
import {AuthProvider} from "./provider";

export const metadata: Metadata = {
  title: "Next Authentication ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>
        {children}
        </AuthProvider>
        </body>
    </html>
  );
}
